### ISSUE TITLE
Feature request: differently sized image groups

### ISSUE THREAD

**Issue by heeplr** [wildlyinaccurate/jekyll-responsive-image#105]
I have 2 types of images: People Portraits and Link Thumbnails.

* Portrait images should have widths: 640, 800, 1024, 2048
* Thumbnail images should have widths: 160, 320, 640

Is there a way I could generate those two sets with jekyll-responsive-image ?

(I'm probably missing something but I couldn't think of an unhackish solution.)

**Comment by wildlyinaccurate** [comment]
Hey! The plugin doesn't support having multiple resize targets at the moment, although this is a pretty nice feature request! I haven't thought this through fully, but perhaps multiple configs would work? For example:

```yaml
responsive_image:
  - name: thumbnails
    template: _includes/thumbnail-image.html
    default_quality: 60
    sizes:
      - width: 160
      - width: 320
      - width: 640
    auto_rotate: true
    strip: true

  - name: portrait
    template: _includes/portrait-image.html
    sizes:
      - width: 640
      - width: 800
      - width: 1024
      - width: 2048
```

And then you would specify which config to use on a per-tag basis:

```twig
{% responsive_image config: portrait path: assets/image.jpg %}
```
