### ISSUE TITLE
Error Finding the template

### ISSUE THREAD

**Issue by asecondwill** [wildlyinaccurate/jekyll-responsive-image#120]
I'm getting this error when trying to use the plugin:

jekyll-responsive-image/renderer.rb:25:in `read': Is a directory @ io_fread jekyll-responsive-image/renderer.rb:25:in `read': Is a directory @ io_fread - /Users/will/Sites/app/site2/my-awesome-site

`
https://github.com/wildlyinaccurate/jekyll-responsive-image/blob/dda6d748c8b070b37900d9e0b528d11701808f76/lib/jekyll-responsive-image/renderer.rb#L25`

So it seems i've bungled my config for the template location?
```

  responsive_image:
    template: _includes/responsive-image.html
    sizes:
      - width: 320
      - width: 480
      - width: 800
```

and including the tag:

`  {% responsive_image path: assets/images/moi-2.webp  %}`

The file is here: 

_includes/responsive-image.html

so no leading **_** unlike my other includes.

Gems:

jekyll-responsive-image (1.6.0)
jekyll (4.3.3)

What have i done wrong?
