### ISSUE TITLE
Pass resize configuration object (or reference to one) via the tag/block

### ISSUE THREAD

**Issue by saulhardman** [wildlyinaccurate/jekyll-responsive-image#18]
Hopefully that title makes sense.

Rather than only setting resize configurations via `_config.yml` I find myself needing to resize different images in different ways. Content images and author profile photos for example. For now it's possible for me to just add all configurations required by every 'type' or 'context' of image, but this results in unnecessary images being created.

Ideally I would like to be able to create image size types – that are arrays of resize configurations – and reference those types in the `responsive_image` or `responsive_image_block` tags. E.g.:

```liquid
<!-- YYYY-MM-DD-some-post.md -->
{% responsive_image path: 'assets/test.png' alt: 'Lorem ipsum...' type: 'content' %}
```

```yaml
# config.yml
responsive_image:
  sizes:
    content:
      - width: 480
      - width: 768
    author:
      - width: 120
      - width: 240
```

Either that, or pass an array of resize configurations directly into the tag e.g.:

```liquid
{% responsive_image_block %}
  path: 'assets/test.png'
  alt: 'Lorem ipsum...'
  sizes: # might not be the best name, as it conflicts with the srcset sizes attribute
    - width: 480
    - width: 768
{% endresponsive_image_block %}
```

Thoughts on this?

I'm willing to contribute, but would need some briefing on where it would be best to add such functionality and some hand-holding as Ruby isn't my primary language.

**Comment by wildlyinaccurate** [comment]
This is an interesting idea. If we can implement it in a backwards-compatible way (i.e. everybody's "old" config and content still works perfectly fine) then I would be okay with it.

I'm slightly worried that it adds a lot of complexity to the plugin, though. I think right now it's really easy to copy the sample config and just throw a bunch of `{% responsive_image path: 'assets/test.png' %}` around the place. Adding something like image types just increases the cognitive load required to use the plugin.

**Comment by saulhardman** [comment]
Thanks for the response @wildlyinaccurate. I appreciate your concern, but I think it's only an issue if it's not implemented as an optional extra. Responsive image solutions can be somewhat complex and sometimes the tooling will reflect this (whilst taking the edge off–which your plugin certainly does!).

Would you agree that the image resize types is more elegant? If so, we can follow that hypothetical route. Perhaps it could be suggested as an alternate implementation or syntax for the resize configurations? E.g.:

```yaml
# _config.yml (without types)
responsive_image:
  sizes:
    - width: 160
    - width: 320
    - width: 480
    - width: 768
    - width: 1280
```

```yaml
# _config.yml (with types)
responsive_image:
  sizes:
    logo:
      - width: 160
      - width: 320
    default:
      - width: 480
      - width: 768
      - width: 1280
```

If a type attribute is omitted from the tag or block, but `sizes` has been configured using types, then we can use the default.

I presume we can fork the logic depending on whether `sizes` has keys (is a hash?) or is an array?

I'm going to take a deeper look at the source code now, so hopefully I'll be able to answer my own questions soon!
