### ISSUE TITLE
Paths not relative to configured source

### ISSUE THREAD

**Issue by sarahquigley** [wildlyinaccurate/jekyll-responsive-image#33]
I have a project where I'm using the 'source' configuration option offered by Jekyll to change the directory which Jekyll will read files from when serving / building my project. (See https://jekyllrb.com/docs/configuration/ for details.)

I have found that this plugin does not respect this configuration when locating images by their path, and thus gives an 'Invalid image path' error when it should not. It would great if support for this config option could be added to this plugin.

Thanks so much!

**Comment by wildlyinaccurate** [comment]
Thanks for reporting this! I'm working on it right now.

**Comment by sarahquigley** [comment]
That's great @wildlyinaccurate! Thanks for being so quick to address issues. If only all project maintainers were so ... responsive. 😄

**Comment by wildlyinaccurate** [comment]
> so ... responsive

![](http://i.giphy.com/l2SpVy7i0IEIH8RKo.gif)

I've made a start on the groundwork in #34 but it's proving a bit fiddly so I might not have a fix ready today.

**Comment by sarahquigley** [comment]
No worries! It's great that you've made a start on it - it looks like you're making good progress. Look forward to the fix whenever you've got it ready. Thanks again.

**Comment by wildlyinaccurate** [comment]
Okay, I _think_ I've managed it. I only have one site nowadays which I can use to test this stuff though. It would be a huge help if you could install version `1.0.0.pre3` of the gem and let me know if that works as you'd expect it to? Thanks!

**Comment by sarahquigley** [comment]
@wildlyinaccurate Excellent! I can definitely test on my site - either tonight or tomorrow - I'll report back once I've done so. Will be in touch soon with the results. You're a 🌟 .

**Comment by sarahquigley** [comment]
@wildlyinaccurate So I installed version `1.0.0.pre3` on the project where I'm using the source config option. I encountered an issue which I'll describe.

Here is a sample of an image path that is now being generated by version `1.0.0.pre3` - it is not quite formulated right, with the `src/uploads` of the path repeated twice:
`/Users/sarah/Code/milk-mustache/src/uploads/resized/src/uploads/posts/recipes/2012-05-05-rainbow-salad-with-bulgur-wheat-and-beans/480`

![screen shot 2016-09-26 at 22 17 08](https://cloud.githubusercontent.com/assets/1569881/18858192/295f92cc-8438-11e6-93f8-4da177b20ce4.png)

So some details of my configuration:
My configured source is a directory `src`.
Here is my config for `jekyll-responsive-image`.
```
# https://github.com/wildlyinaccurate/jekyll-responsive-image
responsive_image:
  template: _includes/image.html
  default_quality: 90
  sizes:
    - width: 480
    - width: 620
    - width: 768
    - width: 1000
    - width: 1400
    - width: 2000
  base_path: uploads
  output_path_format: uploads/resized/%{dirname}/%{width}/%{basename}
```
So unless I have misunderstood how to correctly configure this plugin, I think this fix still has a few issues to be ironed out.

Thanks so much again for working on this fix - so appreciated!
