### ISSUE TITLE
Possible to copy files which do not need resizing

### ISSUE THREAD

**Issue by dimitrieh** [wildlyinaccurate/jekyll-responsive-image#52]
Hi is this possible?

At the moment i got a few image files over 5 mb, which are correctly resized and copied over to their new location.

However when an image is below that target resolution, it doesn't copy it over. I would like that to be possible or enforced.

cc: @wildlyinaccurate

**Comment by wildlyinaccurate** [comment]
Jekyll should already copy these files across, unless you are explicitly ignoring them in your Jekyll configuration.

**Comment by anthonygore** [comment]
I agree, this would be handy. Your assets folder structure is not going to necessarily be the same as the folder structure of the outputted files.

**Comment by wildlyinaccurate** [comment]
I'm not sure that I fully understand the issue. Is it that the plugin does not resize images to be larger than their original dimensions?

**Comment by mezpahlan** [comment]
Just weighing in on this as I *think* I have the same issue.

Here's the relevant section from my `_config.yml`

```
# Jekyll Responsive Image settings
responsive_image:
  template: _includes/common/responsive-image.html
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90
```
This is based on the example in your README. For *most* of my images this works as expected. However for images under 480 width nothing happens. By that I mean no images are placed in the `resized` array. Since the original images are not outputted to the output folder, they are not then transferred over to the compiled site.

Now I suppose what I could do is add a smaller width and force the `next unless needs_resizing?(img, width)` logic to kick in, but as an alternative could you copy over the un-resized image so that it appears in the `resized` array and can be referenced in for loops in the template?

It looks like @zhannon has done something along these lines in his fork. Do you mind taking another look?

Given: An image whose width is smaller than the lowest width configuration in `_config.yml`
When: I run the responsive image plugin
Then: The image is available in the output folder
