### ISSUE TITLE
NoMethodError: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by peter-sc** [wildlyinaccurate/jekyll-responsive-image#77]
Hello,

I'd like to use jekyll-responsive-image on Win10, linux subsystem. If I enable this plugin, I can't build and the error is:

jekyll 3.8.4
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

bundle exec jekyll build --trace -V
  Logging at level: debug
Configuration file: /mnt/c/Users/user/website/_config.yml
             Theme: jekyll-theme-feeling-responsive
      Theme source: /var/lib/gems/2.5.0/gems/jekyll-theme-feeling-responsive-1.0.6
         Requiring: jekyll-menus
         Requiring: jekyll-responsive-image
            Source: /mnt/c/Users/user/website
       Destination: /mnt/c/Users/user/website/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       EntryFilter: excluded /Gemfile
       EntryFilter: excluded /Gemfile.lock
       EntryFilter: excluded /vendor/bundle/bin
       EntryFilter: excluded /vendor/bundle/build_info
       EntryFilter: excluded /vendor/bundle/cache
       EntryFilter: excluded /vendor/bundle/doc
       EntryFilter: excluded /vendor/bundle/extensions
       EntryFilter: excluded /vendor/bundle/gems
       EntryFilter: excluded /vendor/bundle/specifications
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
NoMethodError: undefined method `each' for nil:NilClass
  /var/lib/gems/2.5.0/gems/jekyll-responsive-image-1.5.2/lib/jekyll-responsive-image/extra_image_generator.rb:11:in `generate'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:175:in `block in generate'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:173:in `each'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:173:in `generate'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:70:in `process'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.4/lib/jekyll/command.rb:28:in `process_site'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:65:in `build'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:36:in `process'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /var/lib/gems/2.5.0/gems/jekyll-3.8.4/exe/jekyll:15:in `<top (required)>'
  /usr/local/bin/jekyll:23:in `load'
  /usr/local/bin/jekyll:23:in `<top (required)>'

Thanks,
Peter

**Comment by wildlyinaccurate** [comment]
Please can you paste the `responsive_image` section of your _config.yml?

**Comment by peter-sc** [comment]
Hi, here is the config stripped of #.
```
responsive_image:
  template: _includes/responsive-image.html
  default_quality: 90
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90

	  auto_rotate: false
  strip: true
  base_path: images
  output_path_format: images/resized/%{width}/%{basename}
  save_to_source: false
  cache: false
  extra_images:
```
