### ISSUE TITLE
BUG: Image render gets skipped if using the `--I` parameter

### ISSUE THREAD

**Issue by jhogue** [wildlyinaccurate/jekyll-responsive-image#99]
I have a project with A LOT of images and have set up my publishing workflow to use _stage as my local instance, and _prod is checked against the server for any new changes. I have done this in Jekyll with two different config files — _config.yml and _config_prod.yml. Both files are almost identical, with the exception of the URL and destination parameters. 

The settings for responsive-image in both files are as follows: 

```
responsive_image:
  template: _includes/responsive-image.html
  default_quality: 88
  sizes:
    - width: 480
      quality: 80
    - width: 800
  auto_rotate: false
  strip: true
  base_path: property-img/
  output_path_format: property-img/r/%{width}/%{basename}
  save_to_source: false
  cache: true
```

When I run the `jekyll serve` command, I get a "r" folder where it should be in `_stage`. When I run my production command, `JEKYLL_ENV=production jekyll build --config _config_prod.yml --I` the "r" folder does not show up and get rendered. When I remove the `--I` parameter, it does… but that will render the entire folder brand new every time, as well as ALL my images again, which is what I want to avoid by using the `--I` parameter (preferable to upload only what's new, right now I have 464mb of images that I'd like to avoid uploading if I am just making an HTML page change).

Any pointers would be great. I'll experiment with the `cache` setting, as I have a hunch changing it might yield a different result.
